name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: vishalk13acr
  AKS_RESOURCE_GROUP: vishal
  AKS_CLUSTER_NAME: smartweatheraks
  IMAGE_NAME: devops-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker image to ACR
        run: |
          az acr build --registry $ACR_NAME --image $IMAGE_NAME:latest .

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/devops-app
