---
- name: Deploy to Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Apply deployment
      kubernetes.core.k8s:
        state: present
        src: ../k8s/deployment.yml

    - name: Apply service
      kubernetes.core.k8s:
        state: present
        src: ../k8s/service.yml
